image: node:16

# Workflow Configuration

pipelines:
  default:
    - parallel:
        - step:
            name: Build and Test
            caches:
              - node
            script:
              - npm install
              - npm run build
        - step:
            name: Lint the node package
            script:
              - npm install eslint
              - npm run lint
            caches:
              - node
  branches:
    main:
      - step:
          name: Build and Test
          caches:
            - node
          script:
            - npm install
            - npm run build
      - step:
          name: Security Scan
          script:
            # Run a security scan for sensitive data.
            # See more security tools at https://bitbucket.org/product/features/pipelines/integrations?&category=security
            - pipe: atlassian/git-secrets-scan:0.5.1
      - step:
          name: Deploy to production
          deployment: production
          script:
            - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD:master
